name = "example"
type = "javascript"
workers_dev = false
route = "example.com/*"
account_id = "account id"
zone_id = "zone id"

kv-namespaces = [
    { binding = "wranglerKV", id = "06779da6940b431db6e566b4846d64db" }
]

[vars]
variable1 = "somevalue"

[secrets]
mysecret = "not4u"

[secrets.foo]
bar = 'shhh'
